### ISSUE TITLE
Undefined name 'last_position' in update_user_event_scores.py

### ISSUE THREAD

**Issue by cclauss** [michaelyoungstrom/golfpool#1]
[flake8](http://flake8.pycqa.org) testing of https://github.com/michaelyoungstrom/golfpool on Python 3.7.1

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./players/management/commands/update_user_event_scores.py:65:34: F821 undefined name 'last_position'
                event.position = last_position
                                 ^
1     F821 undefined name 'last_position'
1
```
__E901,E999,F821,F822,F823__ are the "_showstopper_" [flake8](http://flake8.pycqa.org) issues that can halt the runtime with a SyntaxError, NameError, etc. Most other flake8 issues are merely "style violations" -- useful for readability but they do not effect runtime safety.
* F821: undefined name `name`
* F822: undefined name `name` in `__all__`
* F823: local variable name referenced before assignment
* E901: SyntaxError or IndentationError
* E999: SyntaxError -- failed to compile a file into an Abstract Syntax Tree

**Comment by michaelyoungstrom** [comment]
Thanks @cclauss. Fixed and closing
